id = "one-dark-extended"
name = "One Dark Extended Theme"
version = "0.0.1"
schema_version = 1
authors = ["uonick <themes@uonick.com>"]
description = "One Dark Extended theme for Zed"
repository = "https://github.com/uonick/zed-one-dark-extended"